#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: static/home.html.twig
